---
nginx-ingress:
  controller:
    appprotect:
      enable: true
    appprotectdos:
      enable: true
    enableSnippets: true
    image:
      repository: ghcr.io/a4n0nym0u5/nginx-plus-ingress
      tag: 3.0.2-SNAPSHOT-40e3a2b
    nginxplus: true
    nginxStatus:
      allowCidrs: 0.0.0.0/0
      port: 9000
    readyStatus:
      initialDelaySeconds: 30
    serviceAccount:
      imagePullSecretName: ghcr
  prometheus:
    create: true
  serviceInsight:
    create: true
